In [3]:
import numpy as np 
#array operation
arr = np.array([1,2,3,4])
print(arr,type(arr),arr.shape)

arr2=np.array([1,2,3,4,'prime'])
print(arr2,type(arr2),arr.shape)

arr2D =np.array([[1,2,3],[4,5,6,],[7,8,9]])
print(arr2D,type(arr2D),arr2D.shape)

[1 2 3 4] <class 'numpy.ndarray'> (4,)
['1' '2' '3' '4' 'prime'] <class 'numpy.ndarray'> (4,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3)


In [8]:
#2d array aoperation s 
arr2D = np.array([[1,2,3],[3,4,5],[5,6,7]])
print(np.sum(arr2D))

sumofcolums = np.sum(arr2D, axis = 0)
print(sumofcolums)

sumofrows = np.sum(arr2D, axis = 1)
print(sumofrows)

print( arr2D[0:2, 1:2] )

36
[ 9 12 15]
[ 6 12 18]
[[2]
 [4]]


In [21]:
 #3d arraay
arr3D=np.array([[[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,7]]])
print(arr3D,arr3D.shape)

#indexing
print(arr3D[1,1,1])

#slicing
arr3D[:,0,:] = 15
print(arr3D)


[[[1 2]
  [2 3]
  [3 4]]

 [[4 5]
  [5 6]
  [6 7]]] (2, 3, 2)
6
[[[15 15]
  [ 2  3]
  [ 3  4]]

 [[15 15]
  [ 5  6]
  [ 6  7]]]
