In [4]:
#vectorization and Broadcasting
import numpy as np 

# vectorization
arr = np.array([1,2,3,4,5,6])
arr2=np.array([7,8,9,0,1,2])
print(arr ** 2)
print(arr + arr2)




[ 1  4  9 16 25 36]
[ 8 10 12  4  6  8]


In [5]:
#Broadcasting
print(arr + 5)

[ 6  7  8  9 10 11]


In [8]:
#normalize

arr2D=np.array([[1,2],[3,4]])
mean=np.mean(arr2D)
stddev=np.std(arr2D)
normalized=(arr2D-mean)/stddev
print(normalized)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
